### ISSUE TITLE
Option to include error message when invoking CARGO_OPEN command

### ISSUE THREAD

**Issue by casey** [alopatindev/cargo-limit#12]
I found that jumping to error locations could be a little bit disruptive, for example if you're in insert mode, so I'm trying to get cargo-limit to populate vim's quickfix list instead.

I'm using `:cgetexpr` to populate the quickfix list without jumping to the first entry, which works well. It would be nice to include the error messages with each entry, so I was wondering if there was some way that these could be included in the arguments to `CARGO_OPEN`.

Something like `FILE:LINE:COLUMN:ERROR_MESSAGE` would be great, but that would break existing users.

**Comment by casey** [comment]
Some more details, in case anyone is interested. The command I run is:

```
nvr -c "cgetexpr ['<LOCATION>', '<LOCATION>'…] | cclose"
```

`cclose` is to avoid opening the quickfix list. I also set the error format to be compatible with the format that `cargo-limit` produces:

```
set errorformat=%f:%l:%c
```

Once the quickfix list is populated, normal quickfix commands like `:cnext` and `:cprev` can be used to navigate between errors.

**Comment by alopatindev** [comment]
Thanks for reporting this! I noticed this disruptive behavior specifically during file editing.

I personally don't use quickfix list, but just in case if you haven't discovered that yet, `:cnext` and `:cprev` already work using `autozimu/LanguageClient-neovim` + `rust-analyzer`.

> but that would break existing users

It will, but this feature is not released yet, so it's fine to break it for now. I was waiting for a potential need to add something to cargo-limit/Neovim communication, so it'd be reasonable enough to switch to json, which will allow adding new things without breaking users in future.

So we're switching to json now (which is now passed to stdin instead of arguments, as arguments length seems to be slightly limited at least on Windows) and changing behavior a bit:
1. To be less disruptive, Neovim will open/switch tabs with files on given lines and columns only if:
- current mode is normal (which excludes modes like insert, replace, visual and command-line editing)
- current tab contains file from project directory (which means something like netrw or fzf is not currently being used)
- current file is saved/unmodified (which means none of the editing commands were just used, like `dl`).

So basically the idea is to predict whether there's no input activity is going on in Neovim right now.

2. `CARGO_OPEN` is now `CARGO_EDITOR` (in order to not break existing users) and it's now set to `_cargo-limit-open-in-nvim` by default, which is a new program, written in Rust and which is installed automatically with [new Neovim plugin](https://github.com/alopatindev/cargo-limit/blob/master/EDITOR-INTEGRATION.md). So now there's no dependence on bash anymore (which is good for Windows users, crossplatform enough and doesn't require installing anything additional on a fresh OS).

I guess you can still transform new format to old one with something like `jq --raw-output '. as $root | $root | .files[] | [ $root.workspace_root + "/" + .relative_path, (.line | tostring), (.column | tostring) ] | join(":")'` if you need.

I'll think about adding compiler messages to the new format now.

**Comment by casey** [comment]
That all sounds great. I have an unrelated suggestion, but I opened #15 since it's not related to including the error message.
