### ISSUE TITLE
Consistent order of output from multiple test suites

### ISSUE THREAD

**Issue by michaeljones** [alopatindev/cargo-limit#50]
Big fan of the project. I use this a lot and find it very helpful. Thank you for making it.

I'm currently fixing some compile errors across a test suite with the command:
```
cargo ltest --no-fail-fast
```
and I'm getting a different file's errors at the bottom each run. It would be nice if I could work my way through the errors knowing that I'll get the same error/file at the bottom each time unless it is fixed and then I'm on to the next one.

I imagine it would involve sorting the output by the build target name, or something like that. Not  sure. I don't have a clear idea of how cargo-limit currently operates so I'm not sure what is possible.

This might not fit in the scope of the project in which case no worries but I thought it was kind of related to the goal of presenting compiler output in a more useful way. Perhaps there is already a way to achieve this. I've experimented with using `--jobs 1` but that didn't give the desired result.

**Comment by michaeljones** [comment]
Thank you for the quick reply. I'll try to re-create some testing errors and see if this helps later today or tomorrow.

**Comment by michaeljones** [comment]
From what I can tell that doesn't seem to be fixing it. I've tried repeatedly running:
```
find src | xargs touch && cargo ltest --no-fail-fast -- --test-threads=1
```
In a project with more than two integration tests in the `tests` folder next to `src` where compile errors have been introduced into two of the test files. 

From what I can tell, `--test-threads` is not explicitly documented (though it is covered) in the `cargo test` documentation (https://doc.rust-lang.org/cargo/commands/cargo-test.html) as it is a flag for the compiled test binaries rather than for `cargo test` itself. But if it is a flag for the test binaries then it is unlikely to impact the building of the tests themselves and I think my issue is at build time.

Honestly, this issue of mine has not come up much at all so it is pretty manageable. I think that `--jobs=1` should solve the problem is the build graph is deterministic but I thought I tried it and it didn't work. A further issue is that it slows down the compilation quite a lot on a machine that could be using many cores.

Just tried it again and running:
```
find src | xargs touch && cargo ltest --jobs=1
```
Prints errors for different files on two consecutive runs. Curious!

**Comment by alopatindev** [comment]
Ok, that's sad.

It's currently not possible to implement in cargo-limit, due to [lack of stable API for cargo test output](https://www.reddit.com/r/rust/comments/11cd7mk/machine_readable_output_from_cargo_test_still_no/).

Something like [serial_test](https://github.com/palfrey/serial_test) might still help.

**Comment by michaeljones** [comment]
Thanks for the response. It is really no issue if cargo-limit is not well placed to handle it or if it isn't generally possible. 

I want to check that we're on the same page though. My concern is with compiler output whilst compiling the tests rather than test output when running the tests. 

I imagine it might be the same as if there are multiple non-test build targets but I haven't check that case. It is possible that if you have multiple binary entries in Cargo.toml and compilation errors in each binary source then you'd get an compilation error for a different file each time you tweak and re-compile. I'm not sure though.

That feels closer to what cargo-limit is currently doing but in truth I have no idea how cargo-limit does what it does so it maybe well still be impossible. I just wanted to check :)

**Comment by alopatindev** [comment]
For some reason I was thinking about test output, while your issue is during compile time 🤦

Yeah, I guess it's something we can't control either: cargo-limit already sorts whatever cargo/rustc provides, but it can't control order of compilation.

I guess it's not designed to be used that way, since crate is a [compilation unit](https://doc.rust-lang.org/rust-by-example/crates.html), not an individual `.rs` file.

However, if you'd have a workspace of crates and several compilation issues across different crates — then there is some kind of control: you can decide which crate you want to compile with `cargo ltest -p something`.

**Comment by michaeljones** [comment]
I'll try to keep that in mind. Thanks for engaging with the issue. I appreciate you spending the time. I'll close now.
